### PR TITLE
Change goog.module sniffing limit to 50k.

### PR DESCRIPTION
**Pull request by sam-mccall**
The limit is somewhat arbitrary, this is just for consistency with some other tools.

### CODE REVIEW

**Comment by wallw-dev** [comment]
This also fixes support for running the coverage preprocessor before the googmodule one.

**Comment by johnjbarton** [comment]
If this is arbitrary, what is the motivation for the change?

**Comment by schmidtk** [comment]
> If this is arbitrary, what is the motivation for the change?

@johnjbarton `goog.module` calls are at the top of an original source file, but other preprocessors such as code coverage may wrap the source and prevent this from finding the call. Using this preprocessor first also modifies the source, which will unfortunately breaks coverage reports.

I agree with @sam-mccall that the limit may have been arbitrarily selected and worked for known use cases, but it does break in this case.

**Comment by wallw-dev** [comment]
Since @sam-mccall does not appear to be active on this, would it be preferable for me to open a new PR with this change and the conflict resolved?

**Comment by johnjbarton** [comment]
Sure you can do that.

**Comment by sam-mccall** [comment]
Sorry for missing the comments. I'm indeed not really active on this anymore, thanks @wallw-bits for picking this up.

I looked up the reason I originally sent this: we were using several implementations in go/c++/java/JS including this one, that all had different limits.
Go had a limit of 2k and this broke some files due to long LICENSE + file comments. We decided to bump all the implementations up to a presumed-safe limit of 50k, and I sent the PR because having hit 2k, 10k seemed like we might hit it one day.

**Pull request closed without merging**
